# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ToDo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditTask = QtWidgets.QLineEdit(Form)
        self.lineEditTask.setObjectName("lineEditTask")
        self.horizontalLayout.addWidget(self.lineEditTask)
        self.btnAdd = QtWidgets.QPushButton(Form)
        self.btnAdd.setObjectName("btnAdd")
        self.horizontalLayout.addWidget(self.btnAdd)
        self.btnDelete = QtWidgets.QPushButton(Form)
        self.btnDelete.setObjectName("btnDelete")
        self.horizontalLayout.addWidget(self.btnDelete)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableTasks = QtWidgets.QTableWidget(Form)
        self.tableTasks.setColumnCount(2)
        self.tableTasks.setRowCount(0)
        self.tableTasks.setObjectName("tableTasks")
        item = QtWidgets.QTableWidgetItem()
        self.tableTasks.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTasks.setHorizontalHeaderItem(1, item)
        self.tableTasks.horizontalHeader().setDefaultSectionSize(200)
        self.verticalLayout.addWidget(self.tableTasks)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "To-Do List Manager"))
        self.lineEditTask.setPlaceholderText(_translate("Form", "Enter a task..."))
        self.btnAdd.setText(_translate("Form", "Add"))
        self.btnDelete.setText(_translate("Form", "Delete"))
        item = self.tableTasks.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Task"))
        item = self.tableTasks.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Completed"))
